[phases.setup]
nixPkgs = [
  "python3",
  "python3Packages.pip",  # Ensures pip is installed
  "cmake",
  "boost",
  "pkg-config",
  "libjpeg",
  "zlib"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]
